# Generated by Django 4.2.4 on 2023-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
