# Generated by Django 4.2.4 on 2023-09-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aventura', '0001_initial'),
        ('mightyblade', '0002_alter_categoria_aventura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaHabilidade',
        ),
    ]
