# Generated by Django 4.2.4 on 2023-09-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aventura', '0001_initial'),
        ('mightyblade', '0003_rename_categoria_categoriahabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriahabilidade',
            name='aventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_de_habilidade_da_aventura', to='aventura.aventura'),
        ),
        migrations.CreateModel(
            name='TipoHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True)),
                ('aventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_habilidade_da_aventura', to='aventura.aventura')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
